###################???Redis?????###########################
redis:
  #????
  #host: 192.168.43.188
  #port: 6379
  timeout: 6000
  password: 123456
  ###################???redis???????###########################
  sentinel:
    nodes: 192.168.43.234:26379,192.168.43.234:26380,192.168.43.234:26381
    master: mymaster
  ###################???lettuce????????###########################
  lettuce:
    pool:
      max-active:  100 # ????????????????????
      max-idle: 100 # ???????????
      min-idle: 50 # ???????????
      max-wait: 6000 # ??????????????????????
###################???springcache?????###########################
cache:
  redis:
    use-key-prefix: true
    key-prefix: dev
    cache-null-values: false
    time-to-live: 20s
